# -*- coding: utf-8 -*-
# Copyright (C) 2014 Mag. Christian Tanzer All rights reserved
# Glasauergasse 32, A--1130 Wien, Austria. tanzer@swing.co.at
# #*** <License> ************************************************************#
# This module is part of the package TFL.
#
# This module is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This module is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Library General Public License for more details.
#
# You should have received a copy of the GNU Library General Public License
# along with this module; if not, see <http://www.gnu.org/licenses/>.
# #*** </License> ***********************************************************#
#
#++
# Name
#    TFL.Dingbats
#
# Purpose
#    Dingbats as unicode characters
#
# Revision Dates
#    13-Feb-2014 (CT) Creation
#    ««revision-date»»···
#--

from   __future__ import division, print_function
from   __future__ import absolute_import, unicode_literals

from   _TFL       import TFL

### http://www.unicode.org/charts/PDF/U2700.pdf
### http://www.alanwood.net/unicode/dingbats.html

upper_blade_scissors                                                = "\u2701"
black_scissors                                                      = "\u2702"
lower_blade_scissors                                                = "\u2703"
white_scissors                                                      = "\u2704"
white_heavy_check_mark                                              = "\u2705"
telephone_location_sign                                             = "\u2706"
tape_drive                                                          = "\u2707"
airplane                                                            = "\u2708"
envelope                                                            = "\u2709"
raised_fist                                                         = "\u270a"
raised_hand                                                         = "\u270b"
victory_hand                                                        = "\u270c"
writing_hand                                                        = "\u270d"
lower_right_pencil                                                  = "\u270e"
pencil                                                              = "\u270f"
upper_right_pencil                                                  = "\u2710"
white_nib                                                           = "\u2711"
black_nib                                                           = "\u2712"
check_mark                                                          = "\u2713"
heavy_check_mark                                                    = "\u2714"
multiplication_x                                                    = "\u2715"
heavy_multiplication_x                                              = "\u2716"
ballot_x                                                            = "\u2717"
heavy_ballot_x                                                      = "\u2718"
outlined_greek_cross                                                = "\u2719"
heavy_greek_cross                                                   = "\u271a"
open_centre_cross                                                   = "\u271b"
heavy_open_centre_cross                                             = "\u271c"
latin_cross                                                         = "\u271d"
shadowed_white_latin_cross                                          = "\u271e"
outlined_latin_cross                                                = "\u271f"
maltese_cross                                                       = "\u2720"
star_of_david                                                       = "\u2721"
four_teardrop_spoked_asterisk                                       = "\u2722"
four_balloon_spoked_asterisk                                        = "\u2723"
heavy_four_balloon_spoked_asterisk                                  = "\u2724"
four_club_spoked_asterisk                                           = "\u2725"
black_four_pointed_star                                             = "\u2726"
white_four_pointed_star                                             = "\u2727"
sparkles                                                            = "\u2728"
stress_outlined_white_star                                          = "\u2729"
circled_white_star                                                  = "\u272a"
open_centre_black_star                                              = "\u272b"
black_centre_white_star                                             = "\u272c"
outlined_black_star                                                 = "\u272d"
heavy_outlined_black_star                                           = "\u272e"
pinwheel_star                                                       = "\u272f"
shadowed_white_star                                                 = "\u2730"
heavy_asterisk                                                      = "\u2731"
open_centre_asterisk                                                = "\u2732"
eight_spoked_asterisk                                               = "\u2733"
eight_pointed_black_star                                            = "\u2734"
eight_pointed_pinwheel_star                                         = "\u2735"
six_pointed_black_star                                              = "\u2736"
eight_pointed_rectilinear_black_star                                = "\u2737"
heavy_eight_pointed_rectilinear_black_star                          = "\u2738"
twelve_pointed_black_star                                           = "\u2739"
sixteen_pointed_asterisk                                            = "\u273a"
teardrop_spoked_asterisk                                            = "\u273b"
open_centre_teardrop_spoked_asterisk                                = "\u273c"
heavy_teardrop_spoked_asterisk                                      = "\u273d"
six_petalled_black_and_white_florette                               = "\u273e"
black_florette                                                      = "\u273f"
white_florette                                                      = "\u2740"
eight_petalled_outlined_black_florette                              = "\u2741"
circled_open_centre_eight_pointed_star                              = "\u2742"
heavy_teardrop_spoked_pinwheel_asterisk                             = "\u2743"
snowflake                                                           = "\u2744"
tight_trifoliate_snowflake                                          = "\u2745"
heavy_chevron_snowflake                                             = "\u2746"
sparkle                                                             = "\u2747"
heavy_sparkle                                                       = "\u2748"
balloon_spoked_asterisk                                             = "\u2749"
eight_teardrop_spoked_propeller_asterisk                            = "\u274a"
heavy_eight_teardrop_spoked_propeller_asterisk                      = "\u274b"
cross_mark                                                          = "\u274c"
shadowed_white_circle                                               = "\u274d"
negative_squared_cross_mark                                         = "\u274e"
lower_right_drop_shadowed_white_square                              = "\u274f"
upper_right_drop_shadowed_white_square                              = "\u2750"
lower_right_shadowed_white_square                                   = "\u2751"
upper_right_shadowed_white_square                                   = "\u2752"
black_question_mark_ornament                                        = "\u2753"
white_question_mark_ornament                                        = "\u2754"
white_exclamation_mark_ornament                                     = "\u2755"
black_diamond_minus_white_x                                         = "\u2756"
heavy_exclamation_mark_symbol                                       = "\u2757"
light_vertical_bar                                                  = "\u2758"
medium_vertical_bar                                                 = "\u2759"
heavy_vertical_bar                                                  = "\u275a"
heavy_single_turned_comma_quotation_mark_ornament                   = "\u275b"
heavy_single_comma_quotation_mark_ornament                          = "\u275c"
heavy_double_turned_comma_quotation_mark_ornament                   = "\u275d"
heavy_double_comma_quotation_mark_ornament                          = "\u275e"
heavy_low_single_comma_quotation_mark_ornament                      = "\u275f"
heavy_low_double_comma_quotation_mark_ornament                      = "\u2760"
curved_stem_paragraph_sign_ornament                                 = "\u2761"
heavy_exclamation_mark_ornament                                     = "\u2762"
heavy_heart_exclamation_mark_ornament                               = "\u2763"
heavy_black_heart                                                   = "\u2764"
rotated_heavy_black_heart_bullet                                    = "\u2765"
floral_heart                                                        = "\u2766"
rotated_floral_heart_bullet                                         = "\u2767"
medium_left_parenthesis_ornament                                    = "\u2768"
medium_right_parenthesis_ornament                                   = "\u2769"
medium_flattened_left_parenthesis_ornament                          = "\u276a"
medium_flattened_right_parenthesis_ornament                         = "\u276b"
medium_left_pointing_angle_bracket_ornament                         = "\u276c"
medium_right_pointing_angle_bracket_ornament                        = "\u276d"
heavy_left_pointing_angle_quotation_mark_ornament                   = "\u276e"
heavy_right_pointing_angle_quotation_mark_ornament                  = "\u276f"
heavy_left_pointing_angle_bracket_ornament                          = "\u2770"
heavy_right_pointing_angle_bracket_ornament                         = "\u2771"
light_left_tortoise_shell_bracket_ornament                          = "\u2772"
light_right_tortoise_shell_bracket_ornament                         = "\u2773"
medium_left_curly_bracket_ornament                                  = "\u2774"
medium_right_curly_bracket_ornament                                 = "\u2775"
dingbat_negative_circled_digit_one                                  = "\u2776"
dingbat_negative_circled_digit_two                                  = "\u2777"
dingbat_negative_circled_digit_three                                = "\u2778"
dingbat_negative_circled_digit_four                                 = "\u2779"
dingbat_negative_circled_digit_five                                 = "\u277a"
dingbat_negative_circled_digit_six                                  = "\u277b"
dingbat_negative_circled_digit_seven                                = "\u277c"
dingbat_negative_circled_digit_eight                                = "\u277d"
dingbat_negative_circled_digit_nine                                 = "\u277e"
dingbat_negative_circled_number_ten                                 = "\u277f"
dingbat_circled_sans_serif_digit_one                                = "\u2780"
dingbat_circled_sans_serif_digit_two                                = "\u2781"
dingbat_circled_sans_serif_digit_three                              = "\u2782"
dingbat_circled_sans_serif_digit_four                               = "\u2783"
dingbat_circled_sans_serif_digit_five                               = "\u2784"
dingbat_circled_sans_serif_digit_six                                = "\u2785"
dingbat_circled_sans_serif_digit_seven                              = "\u2786"
dingbat_circled_sans_serif_digit_eight                              = "\u2787"
dingbat_circled_sans_serif_digit_nine                               = "\u2788"
dingbat_circled_sans_serif_number_ten                               = "\u2789"
dingbat_negative_circled_sans_serif_digit_one                       = "\u278a"
dingbat_negative_circled_sans_serif_digit_two                       = "\u278b"
dingbat_negative_circled_sans_serif_digit_three                     = "\u278c"
dingbat_negative_circled_sans_serif_digit_four                      = "\u278d"
dingbat_negative_circled_sans_serif_digit_five                      = "\u278e"
dingbat_negative_circled_sans_serif_digit_six                       = "\u278f"
dingbat_negative_circled_sans_serif_digit_seven                     = "\u2790"
dingbat_negative_circled_sans_serif_digit_eight                     = "\u2791"
dingbat_negative_circled_sans_serif_digit_nine                      = "\u2792"
dingbat_negative_circled_sans_serif_number_ten                      = "\u2793"
heavy_wide_headed_rightwards_arrow                                  = "\u2794"
heavy_plus_sign                                                     = "\u2795"
heavy_minus_sign                                                    = "\u2796"
heavy_division_sign                                                 = "\u2797"
heavy_south_east_arrow                                              = "\u2798"
heavy_rightwards_arrow                                              = "\u2799"
heavy_north_east_arrow                                              = "\u279a"
drafting_point_rightwards_arrow                                     = "\u279b"
heavy_round_tipped_rightwards_arrow                                 = "\u279c"
triangle_headed_rightwards_arrow                                    = "\u279d"
heavy_triangle_headed_rightwards_arrow                              = "\u279e"
dashed_triangle_headed_rightwards_arrow                             = "\u279f"
heavy_dashed_triangle_headed_rightwards_arrow                       = "\u27a0"
black_rightwards_arrow                                              = "\u27a1"
three_d_top_lighted_rightwards_arrowhead                            = "\u27a2"
three_d_bottom_lighted_rightwards_arrowhead                         = "\u27a3"
black_rightwards_arrowhead                                          = "\u27a4"
heavy_black_curved_downwards_and_rightwards_arrow                   = "\u27a5"
heavy_black_curved_upwards_and_rightwards_arrow                     = "\u27a6"
squat_black_rightwards_arrow                                        = "\u27a7"
heavy_concave_pointed_black_rightwards_arrow                        = "\u27a8"
right_shaded_white_rightwards_arrow                                 = "\u27a9"
left_shaded_white_rightwards_arrow                                  = "\u27aa"
back_tilted_shadowed_white_rightwards_arrow                         = "\u27ab"
front_tilted_shadowed_white_rightwards_arrow                        = "\u27ac"
heavy_lower_right_shadowed_white_rightwards_arrow                   = "\u27ad"
heavy_upper_right_shadowed_white_rightwards_arrow                   = "\u27ae"
notched_lower_right_shadowed_white_rightwards_arrow                 = "\u27af"
curly_loop                                                          = "\u27b0"
notched_upper_right_shadowed_white_rightwards_arrow                 = "\u27b1"
circled_heavy_white_rightwards_arrow                                = "\u27b2"
white_feathered_rightwards_arrow                                    = "\u27b3"
black_feathered_south_east_arrow                                    = "\u27b4"
black_feathered_rightwards_arrow                                    = "\u27b5"
black_feathered_north_east_arrow                                    = "\u27b6"
heavy_black_feathered_south_east_arrow                              = "\u27b7"
heavy_black_feathered_rightwards_arrow                              = "\u27b8"
heavy_black_feathered_north_east_arrow                              = "\u27b9"
teardrop_barbed_rightwards_arrow                                    = "\u27ba"
heavy_teardrop_shanked_rightwards_arrow                             = "\u27bb"
wedge_tailed_rightwards_arrow                                       = "\u27bc"
heavy_wedge_tailed_rightwards_arrow                                 = "\u27bd"
open_outlined_rightwards_arrow                                      = "\u27be"
double_curly_loop                                                   = "\u27bf"

if __name__ != "__main__" :
    TFL._Export_Module ()
### __END__ TFL.Dingbats
